apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  labels:
    team: a-team
  requirements:
    # - key: "node.kubernetes.io/instance-type" 
    #   operator: In
    #   values: [t2.small, t2.large, t2.xlarge, t2.2xlarge]
    - key: topology.kubernetes.io/zone
      operator: In
      values: [us-west-1a, us-west-1b, us-west-1c] # Zones
    - key: karpenter.sh/capacity-type
      operator: In
      values: [spot]
  limits:
    resources:
      cpu: 1000
  provider:
    tags:
      team: a-team
    instanceProfile: KarpenterNodeInstanceProfile-duke-karpenter-test
  ttlSecondsAfterEmpty: 30
