apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"karpenter.k8s.aws/v1alpha1","kind":"AWSNodeTemplate","metadata":{"annotations":{},"name":"default"},"spec":{"securityGroupSelector":{"karpenter.sh/discovery":"Karpenter-test-03"},"subnetSelector":{"karpenter.sh/discovery":"Karpenter-test-03"}}}
  creationTimestamp: "2023-05-31T11:43:26Z"
  generation: 1
  name: default
  resourceVersion: "554184"
  uid: a0028da9-e0b0-4190-a626-479eeac1aa43
spec:
  securityGroupSelector:
    karpenter.sh/discovery: Karpenter-test-03
  subnetSelector:
    karpenter.sh/discovery: Karpenter-test-03
status:
  securityGroups:
  - id: sg-0792ed5828190d5f4
  - id: sg-07c3aef45b8163c69
  subnets:
  - id: subnet-0d37ec82297b311b6
    zone: us-west-1a
  - id: subnet-09360b7210c9822b0
    zone: us-west-1b
