apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: gpu-shared
spec:
  instanceProfile: KarpenterNodeInstanceProfile-Karpenter-test-03
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 200Gi
        volumeType: gp3
        iops: 3000
        throughput: 200
        deleteOnTermination: true
  tags:
    karpenter.sh/discovery: Karpenter-test-03
    node-type: gpu-shared
    jina.ai/node-type: gpu-shared
  metadataOptions:
    httpEndpoint: enabled
    httpTokens: optional
    httpPutResponseHopLimit: 2
  subnetSelector:
    karpenter.sh/discovery: Karpenter-test-03
  securityGroupSelector:
    karpenter.sh/discovery: Karpenter-test-03
