apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  requirements:
    - key: topology.kubernetes.io/zone
      operator: In
      values: [us-west-1a, us-west-1b] # Zones
    - key: karpenter.sh/capacity-type
      operator: In
      values: ["spot"]
  limits:
    resources:
      cpu: 1000
  provider:
    instanceProfile: KarpenterNodeInstanceProfile-karp-test-05-cluster
    subnetSelector:
      karpenter.sh/discovery: karp-test-05-cluster
    securityGroupSelector:
      karpenter.sh/discovery: karp-test-05-cluster
  ttlSecondsAfterEmpty: 30

