apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      meta.helm.sh/release-name: karpenter
      meta.helm.sh/release-namespace: karpenter
    creationTimestamp: "2023-03-28T09:33:37Z"
    labels:
      app.kubernetes.io/instance: karpenter
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: karpenter
      app.kubernetes.io/version: 0.27.0
      helm.sh/chart: karpenter-v0.27.0
    name: karpenter
    namespace: karpenter
    resourceVersion: "2209805"
    uid: 5bb2588b-a5a6-4c0f-a305-65c7c3cb6a5a
  spec:
    clusterIP: 10.100.123.197
    clusterIPs:
    - 10.100.123.197
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: http-metrics
      port: 8080
      protocol: TCP
      targetPort: http-metrics
    - name: https-webhook
      port: 443
      protocol: TCP
      targetPort: https-webhook
    selector:
      app.kubernetes.io/instance: karpenter
      app.kubernetes.io/name: karpenter
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
