---
apiVersion: v1
kind: ServiceAccount
metadata:
  name:  karpenter-pre-req
---
apiVersion: v1
kind: Namespace
metadata:
  name:  karpenter
---
apiVersion: batch/v1
kind: Job
metadata:
  name: karpenter-pre-req-eksctl-job
spec:
  template:
    metadata:
      labels:
        app: karpenter-setup-eksctl-job
    spec:
      serviceAccountName: karpenter-pre-req
      containers:
      - name: karpenter-setup-eksctl-job
        image: chatwork/eksctl:latest
        env:
          - name: CLUSTER_NAME
            value: "karp-duke"
          - name: ACCOUNT_ID
            value: "844333597536"
          - name: AWS_PROFILE
            value: Nirmata-aws-devtest
        command:
          - /bin/sh
          - -c
          - |
            yum install git -y > /dev/null 2>&1
            git clone https://github.com/anuddeeph1/pre-requisite-karpenter.git
            cd pre-requisite-karpenter/karpenter-pre-req
            chmod +x eksctl-updatecm-sa.sh
            ./eksctl-updatecm-sa.sh $CLUSTER_NAME $ACCOUNT_ID
        volumeMounts:
        - mountPath: /root/.aws
          name: aws-cred
      volumes:
      - name: aws-cred
        hostPath:
          path: ${HOME}/.aws
      restartPolicy: Never

